# This workflow runs tests and checks formatting for the Rust project.
name: Rust CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: cargo test and fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - id: cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: btfly
      - run: cargo test --all-features
      - run: cargo fmt --all --check
